import{a as q,S as P,i as s}from"./assets/vendor-DQq26VV5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();async function d(o,e){const i=await q.get("https://pixabay.com/api/",{params:{key:"53591790-b582ea9c542996630b69812e5",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});return console.log(i.data),i.data.hits}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),E=new P(".photo-card div a",{}),p=document.querySelector(".btn[type=button]");function m(o){const e=o.reduce((i,{likes:l,views:t,comments:r,downloads:n,previewURL:v,largeImageURL:S,tags:w})=>i+`<li class="photo-card">
        <div>
          <a href="${S}">
            <img src="${v}" alt="${w}">
          </a>
        </div>
        <ul>
          <li><p>Likes:<br>${l}</p></li>
          <li><p>Views:<br>${t}</p></li>
          <li><p>Comments:<br>${r}</p></li>
          <li><p>Downloads:<br>${n}</p></li>
        </ul>
      </li>`,"");f.insertAdjacentHTML("beforeend",e),E.refresh()}function $(){f.innerHTML=""}function y(){h.classList.add("is-hidden")}function g(){h.classList.remove("is-hidden")}function a(){p.classList.add("is-hidden")}function b(){p.classList.remove("is-hidden")}function R(){const o=document.querySelector(".gallery .photo-card");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,left:0,behavior:"smooth"})}const O=document.querySelector(".form"),x=document.querySelector(".btn[type=button]"),B=document.querySelector('input[name="search-text"]');let c=1,u="";const L=15;async function I(o){if(o.preventDefault(),u=B.value.trim(),a(),!u){s.info({title:"Info",message:"Поле вводу порожнє",position:"topRight"});return}$(),g();try{c=1;const e=await d(u,c);if(!e.length)throw new Error("Sorry, there are no images matching your search query. Please try again!");m(e),e.length>=L?b():a()}catch(e){s.error({title:"Error",message:e.message||"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{c=2,y()}}async function M(o){o.preventDefault(),a(),g();try{const e=await d(u,c);if(!e.length){s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a();return}m(e),R(),c+=1,e.length<L?(a(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(e){s.error({title:"Error",message:e.message||"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{y()}}O.addEventListener("submit",I);x.addEventListener("click",M);
//# sourceMappingURL=index.js.map
