import{a as q,S as P,i as l}from"./assets/vendor-DQq26VV5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();async function f(o,e){return(await q.get("https://pixabay.com/api/",{params:{key:"53591790-b582ea9c542996630b69812e5",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const h=document.querySelector("ul.gallery"),p=document.querySelector(".loader"),E=new P(".gallery a",{}),m=document.querySelector(".btn[type=button]");function y(o){const e=o.reduce((i,{likes:a,views:t,comments:r,downloads:s,webformatURL:S,largeImageURL:v,tags:w})=>i+`<li class="photo-card">
        <div>
          <a href="${v}">
            <img src="${S}" alt="${w}">
          </a>
        </div>
        <ul>
          <li><p>Likes:<br>${a}</p></li>
          <li><p>Views:<br>${t}</p></li>
          <li><p>Comments:<br>${r}</p></li>
          <li><p>Downloads:<br>${s}</p></li>
        </ul>
      </li>`,"");h.insertAdjacentHTML("beforeend",e),E.refresh()}function $(){h.innerHTML=""}function g(){p.classList.add("is-hidden")}function b(){p.classList.remove("is-hidden")}function u(){m.classList.add("is-hidden")}function L(){m.classList.remove("is-hidden")}function M(){const o=document.querySelector(".gallery .photo-card");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,left:0,behavior:"smooth"})}const O=document.querySelector(".form"),R=document.querySelector(".btn[type=button]"),x=document.querySelector('input[name="search-text"]');let n=1,c="";const B=15;let d;async function C(o){if(o.preventDefault(),c=x.value.trim(),u(),!c){l.info({title:"Info",message:"Поле вводу порожнє",position:"topRight"});return}$(),b();try{n=1;const{totalHits:e,hits:i}=await f(c,n);if(d=Math.ceil(e/B),!i.length)throw new Error("Sorry, there are no images matching your search query. Please try again!");y(i),n>=d?u():L(),n=2}catch(e){l.error({title:"Error",message:e.message||"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{g()}}async function G(o){o.preventDefault(),u(),b();try{const{hits:e}=await f(c,n);y(e),M(),n>=d?(u(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L(),n+=1}catch(e){l.error({title:"Error",message:e.message||"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{g()}}O.addEventListener("submit",C);R.addEventListener("click",G);
//# sourceMappingURL=index.js.map
